language: node_js
node_js:
  - '0.10'
before_install:
  - sudo apt-get update -qq
  - sudo apt-get -y install wget p7zip-full
  - sh ./.runner.sh
  - npm install -g gulp bower
install:
  - bower install
  - npm install
script:
  - gulp build
  - sh ./.deploy.sh
env:
  global:
    - GH_REF: github.com/IBM-Watson/design-library
    - secure: "ZaEkng1TALd1FianddZJmahdIBTW9QBfwOjxaYDG+PkBc8zEBM4pR+BbBzG5UT5huVGJ91SssWL5Xvx+yqWIbY2N1/vFzzCkgAzt+B0vWQim15oezyxtX8sREF3/RjjRzQ9kQ58JyYk6oigwu191eINyVVwn7pjxuApa0gwFcOM="
notifications:
  slack:
    secure: mN+9lpQZPWm1QdUCreWmJ/MQaGi42yTgHQ1yeZJ3iU7NSVMu5uWdcQ5EXjT2+2ge2cCkfzMQb5EeeAXSw20DLggyC+xOcmIZTeYQY3Y8K0Yrky930z/k/IWpn9h5+yRbzYNp+4jWzcQXKMHNJdswVI25BewE4RpqIcxIsoVHGnw=
